baseurl = "/"
languageCode = "en"
contentDir = "content"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
title = "Castlemore Law"
summaryLength = "30"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = "UA-186216710-1"
disqusShortname = "castlemore-law"


# Define the number of posts per page
Paginate = 6

#Hugo version = 0.78.2
#Hugo_version_link = "https://github.com/gohugoio/hugo/releases/tag/v0.78.2/"

#video_link ="https://www.pexels.com/video/a-man-and-a-woman-walking-in-business-suits-4480595/"

[markup]
  [markup.blackFriday]
    plainIDAnchors = true
    hrefTargetBlank = true

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"


# Site Params
[params]

logo = "/images/castlemore-law-white.svg" 
sticky_logo = "/images/castlemore-law-logo.svg"

address = "606 4 St SW #1100, Calgary, AB T2P1T1 | 202-1460 The Queensway, Etobicoke, ON M8Z 1S4"
address_topbar = "ALBERTA | BRITISH COLUMBIA | ONTARIO"
email = "info@castlemorelaw.com"


phone_no = "+1.587.600.1112"
phone_no_url = "15876001112"
fax_no = "+1.587.600.1188"
fax_no_url = "+15876001188"

about_footer = "Castlemore Law’s has an expert team of attorneys in different practice areas and will help you with your legal needs as your personal guide."

page_header = "/images/banner2.jpg"

facebook_url = ""
twitter_url = ""
linkedin_url = ""


siderbar_title = "Castlemore Law"

# Config Array 

brand = [
  "/images/clients/client1.png",
  "/images/clients/client2.png",
  "/images/clients/client4.png",
  "/images/clients/client5.png",
  "/images/clients/client1.png",
  "/images/clients/client6.png"
]

# Meta Data

Description = "Castlemore Law’s has an expert team of attorneys in different practice areas and will help you with your legal needs as your personal guide."
images = ["/images/social.jpg"] # This will use the image called og.png in static/img folder


# copyright
copyright = "By Castlemore Law ."

# main menu

[meun]

[menu]
    ## Menu bar

  [[menu.footer]]
    name = "About Us"
    url = "/about/"
    weight = 1

  [[menu.footer]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  #[[menu.footer]]
    #name = "Attorneys"
    #url = "/attorneys/"
    #weight = 2

  [[menu.footer]]
    name = "Contact Us"
    url = "/contact/"
    weight = 3

  [[menu.footer1]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 1

  [[menu.footer1]]
    name = "Terms of Use"
    url = "/terms-and-condition/"
    weight = 2
